### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Tyh2001** [emojiiii/emojiiii#1]
看你比较擅长前端工程化和 nodejs，因为我最近在和小伙伴一起开发自己的[组件库](https://github.com/Tyh2001/tyh-ui)

看你有参加过 element-plus 的贡献，所以，能不能请你指导一下？

我们参考了 element3、element-plus 等仓库，但有点不太明白，我们的项目是直接是一个 vue3 的项目，和 element 的项目好像不太一样，所以我们有些地方不是很清楚：

- element-plus 的项目是怎么设计的呢？
- element-plus 的项目怎么可以跑起来呢？

期待你的回复，或者也可以加我微信：VirgoTyh

**Comment by emojiiii** [comment]
我最近刚换了新工作，暂时没有太多的时间处理这方面的事情。如果你有兴趣，可以找我们的主力 @sxzz&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emojiiii/emojiiii"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上6:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[emojiiii/emojiiii] Hello (Issue #1)





 
看你比较擅长前端工程化和 nodejs，因为我最近在和小伙伴一起开发自己的组件库
 
看你有参加过 element-plus 的贡献，所以，能不能请你指导一下？
 
我们参考了 element3、element-plus 等仓库，但有点不太明白，我们的项目是直接是一个 vue3 的项目，和 element 的项目好像不太一样，所以我们有些地方不是很清楚：
  
element-plus 的项目是怎么设计的呢？
 
element-plus 的项目怎么可以跑起来呢？
  
期待你的回复，或者也可以加我微信：VirgoTyh
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by emojiiii** [comment]
https://github.com/zouhangwithsweet/vue-components-lib-seed
有兴趣可以看一下这个简易的组件库




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "emojiiii/emojiiii"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月10日(星期四) 晚上6:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[emojiiii/emojiiii] Hello (Issue #1)





 
看你比较擅长前端工程化和 nodejs，因为我最近在和小伙伴一起开发自己的组件库
 
看你有参加过 element-plus 的贡献，所以，能不能请你指导一下？
 
我们参考了 element3、element-plus 等仓库，但有点不太明白，我们的项目是直接是一个 vue3 的项目，和 element 的项目好像不太一样，所以我们有些地方不是很清楚：
  
element-plus 的项目是怎么设计的呢？
 
element-plus 的项目怎么可以跑起来呢？
  
期待你的回复，或者也可以加我微信：VirgoTyh
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tyh2001** [comment]
好滴
