### ISSUE TITLE
[element-plus] 单元测试向大佬求助！！！

### ISSUE THREAD

**Issue by n0liu** [emojiiii/emojiiii#2]
https://github.com/element-plus/element-plus/pull/7560 大佬你好，你让我增加一个单元测试，我第一次尝试做单元测试，今天我用 vitest 跑了一下对单个文件的测试，一直 报 packages/utils/vue/icon.ts 这个文件里面的错误， 我希望能得到你的帮组。

**Comment by emojiiii** [comment]
would you provide some error info in detail?

**Comment by n0liu** [comment]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/44688300/167360152-422c309c-11d3-4b7b-9fad-3ac55bed61c7.png">

**Comment by emojiiii** [comment]
<img width="805" alt="image" src="https://user-images.githubusercontent.com/30518686/167360890-50636d9b-5a80-44c4-ba7c-a68b11b1ae73.png">

It doesn't seem to be a problem!

**Comment by emojiiii** [comment]
can you try to del your `node_modules` and retry install it ?

**Comment by n0liu** [comment]
谢谢大佬，我找到错误产生的原因了。是我本地的node 版本太低了。我现在升级到 16 以上就OK了
