### ISSUE TITLE
[element-plus] 新人想提交pr，求助！！！！

### ISSUE THREAD

**Issue by BarHool** [emojiiii/emojiiii#3]
大佬，我想尝试提交下element-plus的pr，但是现在是不知道应该提交到哪个分支。。。。。

**Comment by emojiiii** [comment]
在你没有仓库权限前：
1. fork 仓库的代码
2. git clone 你刚才fork的仓库
3. 从dev分支切出你的功能分支
4. push你的分支到你fork的仓库内
5. 打开github页面，到你的fork的仓库，你会发现一个pull request，点一下就可以了。

**Comment by BarHool** [comment]
> 在你没有仓库权限前：
> 
> 1. fork 仓库的代码
> 2. git clone 你刚才fork的仓库
> 3. 从dev分支切出你的功能分支
> 4. push你的分支到你fork的仓库内
> 5. 打开github页面，到你的fork的仓库，你会发现一个pull request，点一下就可以了。

感谢大佬！（膜拜）
